paths:
  data_dir: data
  corpus_dir: corpus

recording:
  audio_bitrate: 128000
  video_bitrate_low: 8000000
  video_bitrate_medium: 12000000
  video_bitrate_high: 20000000

sentence:
  # -- Mode de sélection des templates utilisés pendant la session --
  # 0 = mode par défaut : utilise le template 1 et le template 2
  # 1 = utilise uniquement le template 1
  # 2 = utilise uniquement le template 2
  mode: 0

  # Dans le mode par défaut, le nombre de phrases est de longueur d'une des listes composant le template 1 + longueur de la liste des phrases du template 2